# GoReleaser configuration for Dotsync
# Build and release with: goreleaser release --clean

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: dotsync
    main: .
    binary: dotsync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

brews:
  - name: dotsync
    repository:
      owner: hoangtrung99
      name: homebrew-tap
    homepage: "https://github.com/hoangtrung99/dotsync"
    description: "A beautiful TUI for managing dotfiles"
    license: "MIT"
    skip_upload: true
